version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_local
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis_local
    ports:
      - "6379:6379"

volumes:
  mongo_data:
